# Generated by Django 6.1.1 on 2026-09-25 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidadPastilla', models.CharField(max_length=100)),
                ('horaProgramada', models.TimeField()),
                ('horarioSemanal', models.JSONField()),
                ('periodicidad', models.CharField(max_length=50)),
                ('proximoControl', models.DateField(blank=True, null=True)),
                ('confirmadaHoy', models.BooleanField(default=False)),
                ('fechaUltimaConfirmacion', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroINR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorINR', models.FloatField()),
                ('rangoTerapeuticoMin', models.FloatField()),
                ('rangoTerapeuticoMax', models.FloatField()),
                ('estadoAlerta', models.CharField(max_length=20)),
                ('fechaLectura', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
