# Generated by Django 6.1.1 on 2026-10-04 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nombre', 'id']},
        ),
        migrations.AlterModelOptions(
            name='registroinr',
            options={'ordering': ['-fechaLectura', '-id']},
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='periodicidad',
            field=models.CharField(default='semanal', max_length=50),
        ),
        migrations.AlterField(
            model_name='registroinr',
            name='estadoAlerta',
            field=models.CharField(default='sin_evaluar', max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico')], default='paciente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('tomada', 'Tomada'), ('omitida', 'Omitida')], default='tomada', max_length=10)),
                ('dosis', models.CharField(blank=True, default='', max_length=20)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='api.medicamento')),
            ],
            options={
                'ordering': ['-fechaHora', '-id'],
            },
        ),
    ]
